---
- name: JupyterHub SSL setup
  hosts: jupyterhub
  vars_files:
    - vars.yaml
  become: true

  tasks:
    - name: Check current configuration
      ansible.builtin.script: scripts/check_https_config.py {{ enable_ssl | bool }} {{ letsencrypt_email }} {{ letsencrypt_domain }} {{ letsencrypt_test_cert }}
      args:
        executable: python3
      register: configlook
      failed_when: (configlook.rc not in [0, 1])

    - name: Enable SSL
      ansible.builtin.command:
        cmd: tljh-config set https.enabled {{ enable_ssl }}
      when:
        - configlook.rc == 1

    - name: Remove Let's Encrypt email
      ansible.builtin.command:
        cmd: tljh-config unset https.letsencrypt.email
      when:
        - configlook.rc == 1
      register: remove_email
      failed_when: (remove_email.rc not in [0, 1])

    - name: Set Let's Encrypt email
      ansible.builtin.command:
        cmd: tljh-config set https.letsencrypt.email {{ letsencrypt_email }}
      when:
        - configlook.rc == 1
        - enable_ssl

    - name: Remove Let's Encrypt domain
      ansible.builtin.command:
        cmd: tljh-config unset https.letsencrypt.domains
      when:
        - configlook.rc == 1
      register: remove_domain
      failed_when: (remove_domain.rc not in [0, 1])

    - name: Set Let's Encrypt domain
      ansible.builtin.command:
        cmd: tljh-config add-item https.letsencrypt.domains {{ letsencrypt_domain }}
      when:
        - configlook.rc == 1
        - enable_ssl

    - name: Remove Let's Encrypt staging
      ansible.builtin.command:
        cmd: tljh-config unset https.letsencrypt.staging
      when:
        - configlook.rc == 1
      register: remove_staging
      failed_when: (remove_staging.rc not in [0, 1])

    - name: Set Let's Encrypt staging
      ansible.builtin.command:
        cmd: tljh-config set https.letsencrypt.staging true
      when:
        - configlook.rc == 1
        - enable_ssl
        - letsencrypt_test_cert

    - name: Reload configuration (create SSL certificate)
      ansible.builtin.command:
        cmd: tljh-config reload proxy
      when:
        - configlook.rc == 1
