name: Check Terraform formatting

on: [push]

jobs:
  check_format:
    runs-on: ubuntu-latest
    name: Check Terraform formatting
    steps:
      - uses: actions/checkout@v4
      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: infra
